<?php

/**
 * @file
 * Contains kcvv_vv.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use GuzzleHttp\Exception\RequestException;

/**
 * Implements hook_help().
 */
function kcvv_vv_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kcvv_vv module.
    case 'help.page.kcvv_vv':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration between Drupal and Voetbal Vlaanderen API to sync player stats') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function kcvv_vv_cron() {
  $count = \Drupal::service('kcvv_vv.voetbalvlaanderen')->syncPlayersAllTeams();
  \Drupal::logger('kcvv_vv')
    ->notice('Synchronized @count players.', ['@count' => $count]);

  // @TODO : replace with service!!
  $config = \Drupal::config('kcvv_netlify.kcvvnetlify');
  $netlify_build_hook_url = $config->get('kcvv_netlify_build_hook_url');
  $netlify_build_parameters = "?trigger_title=" . urlencode("Synchronized players with VoetbalVlaanderen statistics.");
  try {
    \Drupal::httpClient()
      ->post($netlify_build_hook_url . $netlify_build_parameters);
  }
  catch (RequestException $exception) {
    \Drupal::logger('kcvv_netlify')
      ->error(t('Failed to trigger Netlify build hook due to error "%error"', ['%error' => $exception->getMessage()]));
  }
}
